version: "3"

services:
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

  flask_app:
    build:
      context: .
    container_name: flask_app
    restart: always
    environment:
      POSTGRES_USER: quake_user
      POSTGRES_PASSWORD: quake_pw
      POSTGRES_HOST: postgres
      POSTGRES_DB: quakedb
      PYTHONPATH: /app
      FLASK_APP: app.routes:app
    depends_on:
      - postgres
    volumes:
      - .:/app
    command: pytest tests/
    # command: flask run --host=0.0.0.0 --port=5000

volumes:
  postgres:
  pgadmin:
